<?php

namespace myPocketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * compteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class compteRepository extends EntityRepository
{
}
