<?php

namespace myPocketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * depenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class depenseRepository extends EntityRepository
{
}
