<?php

namespace myPocketBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * revenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class revenuRepository extends EntityRepository {

}
